In [2]:
import pandas as pd
import requests
import numpy as np

In [3]:
response_apfel_subscriptions = requests.get("http://localhost:5050/apfel/subscriptions")
print(response_apfel_subscriptions.status_code)
if response_apfel_subscriptions.status_code == 200:
    print("Request successful!")
else:
    msg = f"Request failed with status code: {response_apfel_subscriptions.status_code}"
    print(msg)
    raise Exception(msg)
df_apfel_subscriptions = pd.DataFrame(response_apfel_subscriptions.json()['events'])
print('Apel Subs shape: ', df_apfel_subscriptions.shape)
print('Apel Subs columns: ', df_apfel_subscriptions.iloc[0])
df_apfel_subscriptions.head()

200
Request successful!
Apel Subs shape:  (1460, 22)
Apel Subs columns:  affiliate_id
amount                                59.99
app_version                           4.1.5
city                                Cardiff
country_code                             GB
currency                                EUR
customer_created_at    2025-02-01T09:56:16Z
customer_email              user23@test.com
customer_uuid                    APF_C00023
device_type                         android
discount_code                        SAVE20
event_id                    APF-2025-000023
event_timestamp        2025-02-01T09:56:16Z
event_type             SUBSCRIPTION_STARTED
internal_ref                    REF-INT-023
postal_code                            CF10
processing_status                 completed
region                                Wales
renewal_period                       yearly
session_id                      sess_aebd07
subscription_type                  standard
tax_amount                             12.0
Name: 0, dtype: object

,affiliate_id,amount,app_version,city,country_code,currency,customer_created_at,customer_email,customer_uuid,device_type,...,event_timestamp,event_type,internal_ref,postal_code,processing_status,region,renewal_period,session_id,subscription_type,tax_amount
0,,59.99,4.1.5,Cardiff,GB,EUR,2025-02-01T09:56:16Z,user23@test.com,APF_C00023,android,...,2025-02-01T09:56:16Z,SUBSCRIPTION_STARTED,REF-INT-023,CF10,completed,Wales,yearly,sess_aebd07,standard,12.0
1,,59.99,4.3.1,Dresden,DE,EUR,2025-02-01T16:58:39Z,user55@email.com,APF_C00055,ios,...,2025-02-01T16:58:39Z,SUBSCRIPTION_STARTED,REF-INT-063,01067,completed,Saxony,yearly,sess_6a9d56,standard,11.4
2,AFF002,119.99,4.1.3,London,GB,EUR,2025-02-01T17:19:48Z,user31@email.com,APF_C00031,web,...,2025-02-01T17:19:48Z,SUBSCRIPTION_STARTED,REF-INT-031,SW1A,completed,England,yearly,sess_676675,premium,24.0
3,AFF003,5.99,4.2.1,Edinburgh,GB,EUR,2025-02-01T18:55:30Z,user75@email.com,APF_C00075,web,...,2025-02-01T18:55:30Z,SUBSCRIPTION_STARTED,REF-INT-095,EH1,completed,Scotland,monthly,sess_d7fa9e,standard,1.2
4,AFF001,59.99,4.1.2,London,GB,EUR,2025-02-02T12:56:02Z,user76@email.com,APF_C00076,android,...,2025-02-02T12:56:02Z,SUBSCRIPTION_STARTED,REF-INT-097,SW1A,completed,England,yearly,sess_5c9e24,standard,12.0

In [4]:
df_apfel_subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   affiliate_id         1460 non-null   str
 1   amount               1460 non-null   object
 2   app_version          1460 non-null   str
 3   city                 1460 non-null   str
 4   country_code         1460 non-null   str
 5   currency             1460 non-null   str
 6   customer_created_at  1460 non-null   str
 7   customer_email       1460 non-null   str
 8   customer_uuid        1460 non-null   str
 9   device_type          1460 non-null   str
 10  discount_code        1460 non-null   str
 11  event_id             1460 non-null   str
 12  event_timestamp      1460 non-null   str
 13  event_type           1460 non-null   str
 14  internal_ref         1460 non-null   str
 15  postal_code          1460 non-null   str
 16  processing_status    1460 non-null   str
 17  region               1460 non-null   str
 18  renewal_period       1460 non-null   str
 19  session_id           1460 non-null   str
 20  subscription_type    1460 non-null   str
 21  tax_amount           1460 non-null   float64
dtypes: float64(1), object(1), str(20)
memory usage: 251.1+ KB

In [5]:
df_apfel_subscriptions.describe()

        tax_amount
count  1460.000000
mean      9.903568
std       8.958190
min       1.140000
25%       1.200000
50%      11.400000
75%      22.800000
max      24.000000

In [6]:
df_apfel_subscriptions.replace('', np.nan, inplace=True)
date_columns = ['customer_created_at', 'event_timestamp']
for col in date_columns:
    df_apfel_subscriptions[col] = pd.to_datetime(df_apfel_subscriptions[col], errors='raise')
numeric_columns = ['amount', 'tax_amount']
for col in numeric_columns:
    df_apfel_subscriptions[col] = pd.to_numeric(df_apfel_subscriptions[col], errors='raise')
df_apfel_subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   affiliate_id         882 non-null    str
 1   amount               1453 non-null   float64
 2   app_version          1460 non-null   str
 3   city                 1460 non-null   str
 4   country_code         1457 non-null   str
 5   currency             1460 non-null   str
 6   customer_created_at  1460 non-null   datetime64[us, UTC]
 7   customer_email       1456 non-null   str
 8   customer_uuid        1460 non-null   str
 9   device_type          1460 non-null   str
 10  discount_code        816 non-null    str
 11  event_id             1460 non-null   str
 12  event_timestamp      1460 non-null   datetime64[us, UTC]
 13  event_type           1460 non-null   str
 14  internal_ref         1460 non-null   str
 15  postal_code          1460 non-null   str
 16  processing_status    1460 non-null   str
 17  region               1460 non-null   str
 18  renewal_period       1460 non-null   str
 19  session_id           1460 non-null   str
 20  subscription_type    1460 non-null   str
 21  tax_amount           1460 non-null   float64
dtypes: datetime64[us, UTC](2), float64(2), str(18)
memory usage: 251.1 KB

In [7]:
df_apfel_subscriptions.describe()

            amount   tax_amount
count  1453.000000  1460.000000
mean     50.848224     9.903568
std      45.963865     8.958190
min       5.990000     1.140000
25%       5.990000     1.200000
50%      59.990000    11.400000
75%     119.990000    22.800000
max     119.990000    24.000000

In [8]:
df_apfel_subscriptions.nunique()

affiliate_id              3
amount                    4
app_version              18
city                      8
country_code              2
currency                  5
customer_created_at     762
customer_email          761
customer_uuid           762
device_type               3
discount_code             4
event_id               1446
event_timestamp        1446
event_type                6
internal_ref           1446
postal_code               8
processing_status         5
region                    8
renewal_period            2
session_id             1446
subscription_type         2
tax_amount                8
dtype: int64

In [ ]:
df_id_agg = df_apfel_subscriptions.groupby('session_id').agg(
    unique_ids=('session_id', 'count'),
).reset_index()
duplicate_session_ids = df_id_agg[df_id_agg['unique_ids'] > 1]['session_id']
duplicate_session_rows = df_apfel_subscriptions[df_apfel_subscriptions['session_id'].isin(duplicate_session_ids)]
duplicate_session_rows

,affiliate_id,amount,app_version,city,country_code,currency,customer_created_at,customer_email,customer_uuid,device_type,...,event_timestamp,event_type,internal_ref,postal_code,processing_status,region,renewal_period,session_id,subscription_type,tax_amount
99,AFF002,12.99,4.2.1,Cardiff,GB,EUR,2025-02-27 07:14:52+00:00,user5@email.com,APF_C00005,ios,...,2025-02-27 07:14:52+00:00,SUBSCRIPTION_STARTED,REF-INT-005,CF10,completed,Wales,monthly,sess_ce4eb9,premium,2.60
100,AFF002,12.99,4.2.1,Cardiff,GB,EUR,2025-02-27 07:14:52+00:00,user5@email.com,APF_C00005,ios,...,2025-02-27 07:14:52+00:00,SUBSCRIPTION_STARTED,REF-INT-005,CF10,completed,Wales,monthly,sess_ce4eb9,premium,2.60
353,AFF001,5.99,4.3.2,London,GB,EUR,2025-02-16 08:05:53+00:00,user61@test.com,APF_C00061,ios,...,2025-05-08 22:19:21+00:00,SUBSCRIPTION_RENEWED,REF-INT-333,SW1A,completed,England,monthly,sess_7fc621,standard,1.20
354,AFF001,5.99,4.3.2,London,GB,EUR,2025-02-16 08:05:53+00:00,user61@test.com,APF_C00061,ios,...,2025-05-08 22:19:21+00:00,SUBSCRIPTION_RENEWED,REF-INT-333,SW1A,completed,England,monthly,sess_7fc621,standard,1.20
364,AFF003,119.99,4.3.4,London,GB,EUR,2025-02-28 16:04:32+00:00,user11@email.com,APF_C00011,android,...,2025-05-10 21:34:53+00:00,SUBSCRIPTION_RENEWED,REF-INT-389,SW1A,completed,England,yearly,sess_d349db,premium,24.00
365,AFF003,119.99,4.3.4,London,GB,EUR,2025-02-28 16:04:32+00:00,user11@email.com,APF_C00011,android,...,2025-05-10 21:34:53+00:00,SUBSCRIPTION_RENEWED,REF-INT-389,SW1A,completed,England,yearly,sess_d349db,premium,24.00
516,NaN,5.99,4.1.0,Dresden,DE,EUR,2025-05-06 18:23:08+00:00,user222@email.com,APF_C00222,web,...,2025-06-20 17:44:43+00:00,SUBSCRIPTION_CANCELLED,REF-INT-476,01067,completed,Saxony,monthly,sess_34059a,standard,1.14
517,NaN,5.99,4.1.0,Dresden,DE,EUR,2025-05-06 18:23:08+00:00,user222@email.com,APF_C00222,web,...,2025-06-20 17:44:43+00:00,SUBSCRIPTION_CANCELLED,REF-INT-476,01067,completed,Saxony,monthly,sess_34059a,standard,1.14
541,AFF002,5.99,4.2.2,Hamburg,DE,EUR,2025-06-27 17:16:35+00:00,user285@email.com,APF_C00285,android,...,2025-06-27 17:16:35+00:00,SUBSCRIPTION_STARTED,REF-INT-530,20095,completed,Hamburg,monthly,sess_77dd02,standard,1.14
542,AFF002,5.99,4.2.2,Hamburg,DE,EUR,2025-06-27 17:16:35+00:00,user285@email.com,APF_C00285,android,...,2025-06-27 17:16:35+00:00,SUBSCRIPTION_STARTED,REF-INT-530,20095,completed,Hamburg,monthly,sess_77dd02,standard,1.14
659,NaN,59.99,4.3.1,Edinburgh,GB,EUR,2025-07-28 22:46:46+00:00,user302@email.com,APF_C00302,android,...,2025-07-28 22:46:46+00:00,SUBSCRIPTION_STARTED,REF-INT-557,EH1,completed,Scotland,yearly,sess_408d88,standard,12.00
660,NaN,59.99,4.3.1,Edinburgh,GB,EUR,2025-07-28 22:46:46+00:00,user302@email.com,APF_C00302,android,...,2025-07-28 22:46:46+00:00,SUBSCRIPTION_STARTED,REF-INT-557,EH1,completed,Scotland,yearly,sess_408d88,standard,12.00
714,AFF002,119.99,4.1.5,Edinburgh,GB,EUR,2025-08-13 19:59:04+00:00,user372@email.com,APF_C00372,android,...,2025-08-13 19:59:04+00:00,SUBSCRIPTION_STARTED,REF-INT-697,EH1,completed,Scotland,yearly,sess_37b748,premium,24.00
715,AFF002,119.99,4.1.5,Edinburgh,GB,EUR,2025-08-13 19:59:04+00:00,user372@email.com,APF_C00372,android,...,2025-08-13 19:59:04+00:00,SUBSCRIPTION_STARTED,REF-INT-697,EH1,completed,Scotland,yearly,sess_37b748,premium,24.00
758,NaN,119.99,4.1.1,Hamburg,DE,EUR,2025-08-13 07:42:46+00:00,user381@email.com,APF_C00381,ios,...,2025-08-21 18:21:36+00:00,SUBSCRIPTION_RENEWED,REF-INT-754,20095,completed,Hamburg,yearly,sess_b8844f,premium,22.80
759,NaN,119.99,4.1.1,Hamburg,DE,EUR,2025-08-13 07:42:46+00:00,user381@email.com,APF_C00381,ios,...,2025-08-21 18:21:36+00:00,SUBSCRIPTION_RENEWED,REF-INT-754,20095,completed,Hamburg,yearly,sess_b8844f,premium,22.80
931,NaN,59.99,4.1.0,Frankfurt,DE,EUR,2025-07-21 12:12:45+00:00,user327@test.com,APF_C00327,web,...,2025-10-09 16:28:22+00:00,SUBSCRIPTION_RENEWED,REF-INT-900,60311,completed,Hesse,yearly,sess_2e797f,standard,11.40
932,NaN,59.99,4.1.0,Frankfurt,DE,EUR,2025-07-21 12:12:45+00:00,user327@test.com,APF_C00327,web,...,2025-10-09 16:28:22+00:00,SUBSCRIPTION_RENEWED,REF-INT-900,60311,completed,Hesse,yearly,sess_2e797f,standard,11.40
1055,AFF001,5.99,4.3.3,London,GB,EUR,2025-03-08 12:39:33+00:00,user101@email.com,APF_C00101,ios,...,2025-11-11 22:38:50+00:00,SUBSCRIPTION_RENEWED,REF-INT-1087,SW1A,completed,England,monthly,sess_ed967a,standard,1.20
1056,AFF001,5.99,4.3.3,London,GB,EUR,2025-03-08 12:39:33+00:00,user101@email.com,APF_C00101,ios,...,2025-11-11 22:38:50+00:00,SUBSCRIPTION_RENEWED,REF-INT-1087,SW1A,completed,England,monthly,sess_ed967a,standard,1.20
1063,NaN,119.99,4.3.1,Cardiff,GB,EUR,2025-08-24 21:27:56+00:00,user351@email.com,APF_C00351,ios,...,2025-11-13 19:27:50+00:00,SUBSCRIPTION_RENEWED,REF-INT-1050,CF10,completed,Wales,yearly,sess_621eac,premium,24.00
1064,NaN,119.99,4.3.1,Cardiff,GB,EUR,2025-08-24 21:27:56+00:00,user351@email.com,APF_C00351,ios,...,2025-11-13 19:27:50+00:00,SUBSCRIPTION_RENEWED,REF-INT-1050,CF10,completed,Wales,yearly,sess_621eac,premium,24.00
1105,NaN,5.99,4.2.1,Munich,DE,EUR,2025-04-06 18:41:24+00:00,NaN,APF_C00157,web,...,2025-11-24 12:59:36+00:00,SUBSCRIPTION_RENEWED,REF-INT-1104,80331,completed,Bavaria,monthly,sess_e27e97,standard,1.14
1106,NaN,5.99,4.2.1,Munich,DE,EUR,2025-04-06 18:41:24+00:00,user157@email.com,APF_C00157,web,...,2025-11-24 12:59:36+00:00,SUBSCRIPTION_RENEWED,REF-INT-1104,80331,completed,Bavaria,monthly,sess_e27e97,standard,1.14
1142,AFF003,5.99,4.3.4,Dresden,DE,EUR,2025-12-03 20:17:26+00:00,user601@email.com,APF_C00601,ios,...,2025-12-03 20:17:26+00:00,SUBSCRIPTION_STARTED,REF-INT-1150,01067,completed,Saxony,monthly,sess_635e77,standard,1.14
1143,AFF003,5.99,4.3.4,Dresden,DE,EUR,2025-12-03 20:17:26+00:00,user601@email.com,APF_C00601,ios,...,2025-12-03 20:17:26+00:00,SUBSCRIPTION_STARTED,REF-INT-1150,01067,completed,Saxony,monthly,sess_635e77,standard,1.14
1202,NaN,12.99,4.3.5,Edinburgh,GB,EUR,2025-08-16 16:41:15+00:00,user394@email.com,APF_C00394,web,...,2025-12-17 06:40:06+00:00,SUBSCRIPTION_RENEWED,REF-INT-1244,EH1,completed,Scotland,monthly,sess_01de37,premium,2.60
1203,NaN,12.99,4.3.5,Edinburgh,GB,EUR,2025-08-16 16:41:15+00:00,user394@email.com,APF_C00394,web,...,2025-12-17 06:40:06+00:00,SUBSCRIPTION_RENEWED,REF-INT-1244,EH1,completed,Scotland,monthly,sess_01de37,premium,2.60

In [63]:
df_id_agg = df_apfel_subscriptions.groupby('customer_uuid').agg(
    unique_ids=('customer_uuid', 'count'),
).reset_index()
duplicate_cust_ids = df_id_agg[df_id_agg['unique_ids'] > 2]['customer_uuid']
duplicate_cust_rows = df_apfel_subscriptions[df_apfel_subscriptions['customer_uuid'].isin(duplicate_cust_ids)].sort_values('customer_uuid')
duplicate_cust_rows

,affiliate_id,amount,app_version,city,country_code,currency,customer_created_at,customer_email,customer_uuid,device_type,...,event_timestamp,event_type,internal_ref,postal_code,processing_status,region,renewal_period,session_id,subscription_type,tax_amount
20,AFF003,119.99,4.1.3,Munich,DE,EUR,2025-02-04 06:47:17+00:00,user1@email.com,APF_C00001,android,...,2025-02-04 06:47:17+00:00,SUBSCRIPTION_STARTED,REF-INT-001,80331,completed,Bavaria,yearly,sess_e70b3e,premium,22.8
258,AFF002,119.99,4.2.4,Dresden,DE,EUR,2025-02-04 06:47:17+00:00,user1@email.com,APF_C00001,android,...,2025-04-16 10:57:38+00:00,SUBSCRIPTION_RENEWED,REF-INT-280,01067,completed,Saxony,yearly,sess_4b76df,premium,22.8
627,AFF002,119.99,4.3.3,Frankfurt,DE,EUR,2025-02-04 06:47:17+00:00,user1@email.com,APF_C00001,ios,...,2025-07-22 21:32:26+00:00,SUBSCRIPTION_RENEWED,REF-INT-567,60311,completed,Hesse,yearly,sess_e3bb60,premium,22.8
1251,AFF002,119.99,4.1.1,Berlin,DE,EUR,2025-02-04 06:47:17+00:00,user1@email.com,APF_C00001,ios,...,2025-12-26 08:51:47+00:00,SUBSCRIPTION_RENEWED,REF-INT-1118,10115,completed,Berlin,yearly,sess_fd633c,premium,22.8
189,AFF001,59.99,4.2.1,Frankfurt,DE,EUR,2025-02-19 14:51:55+00:00,user2@email.com,APF_C00002,web,...,2025-03-25 15:20:05+00:00,SUBSCRIPTION_RENEWED,REF-INT-189,60311,completed,Hesse,yearly,sess_a4fb96,standard,11.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1018,NaN,119.99,4.2.3,Dresden,DE,EUR,2025-11-03 16:03:29+00:00,user559@email.com,APF_C00559,android,...,2025-11-03 16:03:29+00:00,SUBSCRIPTION_STARTED,REF-INT-1066,01067,completed,Saxony,yearly,sess_175e05,premium,22.8
1184,NaN,119.99,4.1.3,Berlin,DE,EUR,2025-11-03 16:03:29+00:00,user559@email.com,APF_C00559,web,...,2025-12-13 16:49:53+00:00,SUBSCRIPTION_RENEWED,REF-INT-1147,10115,completed,Berlin,yearly,sess_b6d529,premium,22.8
1387,AFF002,59.99,4.3.2,Frankfurt,DE,EUR,2026-01-03 07:07:33+00:00,user674@email.com,APF_C00674,web,...,2026-01-26 18:38:42+00:00,SUBSCRIPTION_RENEWED,REF-INT-1393,60311,completed,Hesse,yearly,sess_6fc412,standard,11.4
1277,NaN,59.99,4.2.5,Hamburg,DE,EUR,2026-01-03 07:07:33+00:00,user674@email.com,APF_C00674,android,...,2026-01-03 07:07:33+00:00,SUBSCRIPTION_STARTED,REF-INT-1277,20095,completed,Hamburg,yearly,sess_1cb3fd,standard,11.4
1421,NaN,59.99,4.1.4,Frankfurt,DE,EUR,2026-01-03 07:07:33+00:00,user674@email.com,APF_C00674,android,...,2026-02-06 17:39:46+00:00,SUBSCRIPTION_RENEWED,REF-INT-1433,60311,completed,Hesse,yearly,sess_6c7f73,standard,11.4

In [67]:
df_id_agg = df_apfel_subscriptions.groupby('event_id').agg(
    unique_ids=('event_id', 'count'),
).reset_index()
duplicate_event_ids = df_id_agg[df_id_agg['unique_ids'] > 1]['event_id']
duplicate_event_rows = df_apfel_subscriptions[df_apfel_subscriptions['event_id'].isin(duplicate_event_ids)].sort_values('event_id')
duplicate_event_rows.drop_duplicates()

,affiliate_id,amount,app_version,city,country_code,currency,customer_created_at,customer_email,customer_uuid,device_type,...,event_timestamp,event_type,internal_ref,postal_code,processing_status,region,renewal_period,session_id,subscription_type,tax_amount
99,AFF002,12.99,4.2.1,Cardiff,GB,EUR,2025-02-27 07:14:52+00:00,user5@email.com,APF_C00005,ios,...,2025-02-27 07:14:52+00:00,SUBSCRIPTION_STARTED,REF-INT-005,CF10,completed,Wales,monthly,sess_ce4eb9,premium,2.60
353,AFF001,5.99,4.3.2,London,GB,EUR,2025-02-16 08:05:53+00:00,user61@test.com,APF_C00061,ios,...,2025-05-08 22:19:21+00:00,SUBSCRIPTION_RENEWED,REF-INT-333,SW1A,completed,England,monthly,sess_7fc621,standard,1.20
364,AFF003,119.99,4.3.4,London,GB,EUR,2025-02-28 16:04:32+00:00,user11@email.com,APF_C00011,android,...,2025-05-10 21:34:53+00:00,SUBSCRIPTION_RENEWED,REF-INT-389,SW1A,completed,England,yearly,sess_d349db,premium,24.00
516,NaN,5.99,4.1.0,Dresden,DE,EUR,2025-05-06 18:23:08+00:00,user222@email.com,APF_C00222,web,...,2025-06-20 17:44:43+00:00,SUBSCRIPTION_CANCELLED,REF-INT-476,01067,completed,Saxony,monthly,sess_34059a,standard,1.14
541,AFF002,5.99,4.2.2,Hamburg,DE,EUR,2025-06-27 17:16:35+00:00,user285@email.com,APF_C00285,android,...,2025-06-27 17:16:35+00:00,SUBSCRIPTION_STARTED,REF-INT-530,20095,completed,Hamburg,monthly,sess_77dd02,standard,1.14
659,NaN,59.99,4.3.1,Edinburgh,GB,EUR,2025-07-28 22:46:46+00:00,user302@email.com,APF_C00302,android,...,2025-07-28 22:46:46+00:00,SUBSCRIPTION_STARTED,REF-INT-557,EH1,completed,Scotland,yearly,sess_408d88,standard,12.00
715,AFF002,119.99,4.1.5,Edinburgh,GB,EUR,2025-08-13 19:59:04+00:00,user372@email.com,APF_C00372,android,...,2025-08-13 19:59:04+00:00,SUBSCRIPTION_STARTED,REF-INT-697,EH1,completed,Scotland,yearly,sess_37b748,premium,24.00
758,NaN,119.99,4.1.1,Hamburg,DE,EUR,2025-08-13 07:42:46+00:00,user381@email.com,APF_C00381,ios,...,2025-08-21 18:21:36+00:00,SUBSCRIPTION_RENEWED,REF-INT-754,20095,completed,Hamburg,yearly,sess_b8844f,premium,22.80
931,NaN,59.99,4.1.0,Frankfurt,DE,EUR,2025-07-21 12:12:45+00:00,user327@test.com,APF_C00327,web,...,2025-10-09 16:28:22+00:00,SUBSCRIPTION_RENEWED,REF-INT-900,60311,completed,Hesse,yearly,sess_2e797f,standard,11.40
1063,NaN,119.99,4.3.1,Cardiff,GB,EUR,2025-08-24 21:27:56+00:00,user351@email.com,APF_C00351,ios,...,2025-11-13 19:27:50+00:00,SUBSCRIPTION_RENEWED,REF-INT-1050,CF10,completed,Wales,yearly,sess_621eac,premium,24.00
1055,AFF001,5.99,4.3.3,London,GB,EUR,2025-03-08 12:39:33+00:00,user101@email.com,APF_C00101,ios,...,2025-11-11 22:38:50+00:00,SUBSCRIPTION_RENEWED,REF-INT-1087,SW1A,completed,England,monthly,sess_ed967a,standard,1.20
1105,NaN,5.99,4.2.1,Munich,DE,EUR,2025-04-06 18:41:24+00:00,NaN,APF_C00157,web,...,2025-11-24 12:59:36+00:00,SUBSCRIPTION_RENEWED,REF-INT-1104,80331,completed,Bavaria,monthly,sess_e27e97,standard,1.14
1106,NaN,5.99,4.2.1,Munich,DE,EUR,2025-04-06 18:41:24+00:00,user157@email.com,APF_C00157,web,...,2025-11-24 12:59:36+00:00,SUBSCRIPTION_RENEWED,REF-INT-1104,80331,completed,Bavaria,monthly,sess_e27e97,standard,1.14
1142,AFF003,5.99,4.3.4,Dresden,DE,EUR,2025-12-03 20:17:26+00:00,user601@email.com,APF_C00601,ios,...,2025-12-03 20:17:26+00:00,SUBSCRIPTION_STARTED,REF-INT-1150,01067,completed,Saxony,monthly,sess_635e77,standard,1.14
1202,NaN,12.99,4.3.5,Edinburgh,GB,EUR,2025-08-16 16:41:15+00:00,user394@email.com,APF_C00394,web,...,2025-12-17 06:40:06+00:00,SUBSCRIPTION_RENEWED,REF-INT-1244,EH1,completed,Scotland,monthly,sess_01de37,premium,2.60

In [59]:
len(df_apfel_subscriptions[df_apfel_subscriptions.duplicated()])

13

In [68]:
df_apfel_subscriptions['subscription_type'].unique()

<StringArray>
['standard', 'premium']
Length: 2, dtype: str

In [70]:
df_apfel_subscriptions['event_type'].unique().tolist()

['SUBSCRIPTION_STARTED',
 'SUBSCRIPTION_RENEWED',
 'SUBSCRIPTION_CANCELLED',
 'subscription_started',
 'subscription_renewed',
 'subscription_cancelled']

In [79]:
df_apfel_subscriptions['processing_status'].unique().tolist()

['completed', 'COMPLETED', 'pending', 'processing', 'failed']

In [78]:
df_apfel_subscriptions[df_apfel_subscriptions['currency'] == 'GBP']

,affiliate_id,amount,app_version,city,country_code,currency,customer_created_at,customer_email,customer_uuid,device_type,...,event_timestamp,event_type,internal_ref,postal_code,processing_status,region,renewal_period,session_id,subscription_type,tax_amount
229,AFF003,119.99,4.3.5,Cardiff,GB,GBP,2025-04-13 17:11:28+00:00,user132@email.com,APF_C00132,android,...,2025-04-07 14:41:26+00:00,SUBSCRIPTION_RENEWED,REF-INT-223,CF10,completed,Wales,yearly,sess_49faa3,premium,24.0
559,NaN,12.99,4.2.5,London,GB,GBP,2025-06-27 18:07:55+00:00,user275@email.com,APF_C00275,web,...,2025-07-04 15:06:32+00:00,SUBSCRIPTION_RENEWED,REF-INT-619,SW1A,processing,England,monthly,sess_53b11f,premium,2.6
1404,NaN,NaN,4.1.1,Munich,DE,GBP,2025-07-02 12:47:52+00:00,user329@email.com,APF_C00329,android,...,2026-02-01 19:07:28+00:00,SUBSCRIPTION_RENEWED,REF-INT-1450,80331,completed,Bavaria,yearly,sess_5a88b6,standard,11.4

In [51]:
url = "http://localhost:5050/fenster/subscriptions"
df_fenster_subscriptions = pd.read_csv(url)
print('Fenster Subs shape: ', df_fenster_subscriptions.shape)
print('Fenster Subs columns: ', df_fenster_subscriptions.iloc[0])
df_fenster_subscriptions.head()

Fenster Subs shape:  (1165, 26)
Fenster Subs columns:  id                         FEN-00024
ts               2025-02-01 13:38:59
type                             new
cid                       FEN_C00024
mail                user24@email.com
signup_ts        2025-02-01 13:38:59
ctry                             USA
state                     Washington
zip                            98101
plan                 premium_monthly
ccy                              USD
price                          14.99
tax                              1.2
vat_id                           NaN
campaign_src                  google
utm_medium                    social
utm_campaign                    none
browser                      firefox
os                             linux
screen_res                 1170x2532
lang                           es-MX
tz                              AEST
legacy_flag                    False
migrated_from                    NaN
batch_id                        B001
row_hash                    fb743bc9
Name: 0, dtype: object

,id,ts,type,cid,mail,signup_ts,ctry,state,zip,plan,...,utm_campaign,browser,os,screen_res,lang,tz,legacy_flag,migrated_from,batch_id,row_hash
0,FEN-00024,2025-02-01 13:38:59,new,FEN_C00024,user24@email.com,2025-02-01 13:38:59,USA,Washington,98101,premium_monthly,...,none,firefox,linux,1170x2532,es-MX,AEST,False,NaN,B001,fb743bc9
1,FEN-00033,2025-02-01 14:21:10,new,FEN_C00033,user33@email.com,2025-02-01 14:21:10,GBR,Scotland,EH1,standard_yearly,...,winter_sale,edge,windows,2560x1440,en-AU,GMT,False,NaN,B001,38071775
2,FEN-00065,2025-02-01 16:37:53,renew,FEN_C00039,user39@test.com,2025-02-02 18:16:46,United States,Florida,33101,standard_monthly,...,brand_awareness,firefox,linux,1170x2532,en-AU,EST,False,NaN,B002,c238d657
3,FEN-00063,2025-02-01 19:40:04,renew,FEN_C00034,user34@email.com,2025-02-12 21:59:18,GBR,Wales,CF10,premium_yearly,...,partner_q1,chrome,macos,1366x768,es-MX,CET,False,NaN,B002,6e5d1a78
4,FEN-00078,2025-02-01 21:28:15,renew,FEN_C00053,user53@email.com,2025-02-12 17:07:42,GBR,Wales,CF10,premium_yearly,...,latam_push,edge,windows,1366x768,en-GB,AEST,False,NaN,B002,b8f72a56

In [52]:
df_fenster_subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1165 entries, 0 to 1164
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1165 non-null   str
 1   ts             1165 non-null   str
 2   type           1165 non-null   str
 3   cid            1165 non-null   str
 4   mail           1165 non-null   str
 5   signup_ts      1165 non-null   str
 6   ctry           1164 non-null   str
 7   state          1165 non-null   str
 8   zip            1165 non-null   str
 9   plan           1165 non-null   str
 10  ccy            1165 non-null   str
 11  price          1165 non-null   float64
 12  tax            1165 non-null   float64
 13  vat_id         197 non-null    str
 14  campaign_src   1019 non-null   str
 15  utm_medium     962 non-null    str
 16  utm_campaign   1040 non-null   str
 17  browser        1165 non-null   str
 18  os             1165 non-null   str
 19  screen_res     1165 non-null   str
 20  lang           1165 non-null   str
 21  tz             1165 non-null   str
 22  legacy_flag    1165 non-null   bool
 23  migrated_from  50 non-null     str
 24  batch_id       1165 non-null   str
 25  row_hash       1165 non-null   str
dtypes: bool(1), float64(2), str(23)
memory usage: 228.8 KB

In [53]:
def make_utc(row, column):
    return pd.Timestamp(row[column]).tz_localize(row['tz_clean']).tz_convert('UTC')

df_fenster_subscriptions.replace('', np.nan, inplace=True)
tz_map = {
    'AEST': 'Australia/Sydney',
    'GMT':  'UTC',
    'EST':  'America/New_York',
    'CET':  'Europe/Berlin',
    'PST':  'America/Los_Angeles',
    'CST':  'America/Chicago',
    'JST':  'Asia/Tokyo',
}
df_fenster_subscriptions['tz_clean'] = df_fenster_subscriptions['tz'].map(tz_map).fillna(df_fenster_subscriptions['tz'])
date_columns = ['ts', 'signup_ts']
for col in date_columns:
    df_fenster_subscriptions[col] = pd.to_datetime(df_fenster_subscriptions[col], errors='raise')
    df_fenster_subscriptions[col] = df_fenster_subscriptions.apply(make_utc, axis=1, column=col)
numeric_columns = ['price', 'tax']
for col in numeric_columns:
    df_fenster_subscriptions[col] = pd.to_numeric(df_fenster_subscriptions[col], errors='raise')

df_fenster_subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1165 entries, 0 to 1164
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1165 non-null   str
 1   ts             1165 non-null   datetime64[us, UTC]
 2   type           1165 non-null   str
 3   cid            1165 non-null   str
 4   mail           1165 non-null   str
 5   signup_ts      1165 non-null   datetime64[us, UTC]
 6   ctry           1164 non-null   str
 7   state          1165 non-null   str
 8   zip            1165 non-null   str
 9   plan           1165 non-null   str
 10  ccy            1165 non-null   str
 11  price          1165 non-null   float64
 12  tax            1165 non-null   float64
 13  vat_id         197 non-null    str
 14  campaign_src   1019 non-null   str
 15  utm_medium     962 non-null    str
 16  utm_campaign   1040 non-null   str
 17  browser        1165 non-null   str
 18  os             1165 non-null   str
 19  screen_res     1165 non-null   str
 20  lang           1165 non-null   str
 21  tz             1165 non-null   str
 22  legacy_flag    1165 non-null   bool
 23  migrated_from  50 non-null     str
 24  batch_id       1165 non-null   str
 25  row_hash       1165 non-null   str
 26  tz_clean       1165 non-null   str
dtypes: bool(1), datetime64[us, UTC](2), float64(2), str(22)
memory usage: 237.9 KB

In [54]:
df_fenster_subscriptions.nunique()

id               1154
ts               1154
type                5
cid               630
mail              630
signup_ts        1028
ctry                5
state               8
zip                 8
plan                4
ccy                 1
price               4
tax                 9
vat_id            194
campaign_src        7
utm_medium          5
utm_campaign       10
browser             4
os                  5
screen_res          5
lang                7
tz                  7
legacy_flag         2
migrated_from       1
batch_id           26
row_hash         1154
tz_clean            7
dtype: int64

In [73]:
df_id_agg = df_fenster_subscriptions.groupby('id').agg(
    unique_ids=('row_hash', 'count'),
).reset_index()
duplicate_ids = df_id_agg[df_id_agg['unique_ids'] > 1]['id']
duplicate_rows = df_fenster_subscriptions[df_fenster_subscriptions['id'].isin(duplicate_ids)]
duplicate_rows

,id,ts,type,cid,mail,signup_ts,ctry,state,zip,plan,...,browser,os,screen_res,lang,tz,legacy_flag,migrated_from,batch_id,row_hash,tz_clean
61,FEN-00048,2025-02-18 17:03:15+00:00,new,FEN_C00045,user45@email.com,2025-02-18 17:03:15+00:00,USA,Washington,98101,standard_monthly,...,edge,android,1920x1080,en-GB,GMT,False,NaN,B001,de5dbfcf,UTC
62,FEN-00048,2025-02-18 17:03:15+00:00,new,FEN_C00045,user45@email.com,2025-02-18 17:03:15+00:00,USA,Washington,98101,standard_monthly,...,edge,android,1920x1080,en-GB,GMT,False,NaN,B001,de5dbfcf,UTC
178,FEN-00165,2025-03-27 07:07:55+00:00,new,FEN_C00095,user95@email.com,2025-03-27 07:07:55+00:00,GBR,England,SW1A,premium_monthly,...,firefox,android,1080x2340,en-US,GMT,False,NaN,B004,ae9acf67,UTC
179,FEN-00165,2025-03-27 07:07:55+00:00,new,FEN_C00095,user95@email.com,2025-03-27 07:07:55+00:00,GBR,England,SW1A,premium_monthly,...,firefox,android,1080x2340,en-US,GMT,False,NaN,B004,ae9acf67,UTC
216,FEN-00202,2025-04-10 11:42:59+00:00,new,FEN_C00112,user112@email.com,2025-04-10 11:42:59+00:00,GBR,England,SW1A,standard_yearly,...,chrome,ios,1080x2340,de-DE,CET,False,NaN,B005,c2f682a6,Europe/Berlin
217,FEN-00202,2025-04-10 11:42:59+00:00,new,FEN_C00112,user112@email.com,2025-04-10 11:42:59+00:00,GBR,England,SW1A,standard_yearly,...,chrome,ios,1080x2340,de-DE,CET,False,NaN,B005,c2f682a6,Europe/Berlin
392,FEN-00411,2025-06-11 01:38:53+00:00,renew,FEN_C00024,user24@email.com,2025-02-01 04:38:59+00:00,USA,Washington,98101,premium_monthly,...,chrome,windows,1920x1080,en-US,JST,False,NaN,B009,4f7a91a1,Asia/Tokyo
393,FEN-00411,2025-06-11 01:38:53+00:00,renew,FEN_C00024,user24@email.com,2025-02-01 04:38:59+00:00,USA,Washington,98101,premium_monthly,...,chrome,windows,1920x1080,en-US,JST,False,NaN,B009,4f7a91a1,Asia/Tokyo
500,FEN-00482,2025-07-17 10:55:20+00:00,cancel,FEN_C00045,user45@email.com,2025-02-18 22:03:15+00:00,USA,Texas,75001,standard_monthly,...,chrome,macos,1080x2340,ja-JP,EST,False,NaN,B010,db1f7601,America/New_York
501,FEN-00482,2025-07-17 10:55:20+00:00,cancel,FEN_C00045,user45@email.com,2025-02-18 22:03:15+00:00,USA,Texas,75001,standard_monthly,...,chrome,macos,1080x2340,ja-JP,EST,False,NaN,B010,db1f7601,America/New_York
634,FEN-00589,2025-08-27 13:28:05+00:00,renew,FEN_C00096,user96@test.com,2025-03-07 23:22:25+00:00,GBR,Scotland,EH1,premium_yearly,...,safari,windows,1366x768,en-AU,JST,False,NaN,B012,c3a23811,Asia/Tokyo
635,FEN-00589,2025-08-27 13:28:05+00:00,renew,FEN_C00096,user96@test.com,2025-03-07 23:22:25+00:00,GBR,Scotland,EH1,premium_yearly,...,safari,windows,1366x768,en-AU,JST,False,NaN,B012,c3a23811,Asia/Tokyo
664,FEN-00656,2025-09-08 17:20:56+00:00,renew,FEN_C00208,user208@email.com,2025-06-15 00:57:05+00:00,GBR,England,SW1A,premium_monthly,...,edge,ios,1080x2340,ja-JP,EST,False,NaN,B014,3965f26b,America/New_York
665,FEN-00656,2025-09-08 17:20:56+00:00,renew,FEN_C00208,user208@email.com,2025-06-15 00:57:05+00:00,GBR,England,SW1A,premium_monthly,...,edge,ios,1080x2340,ja-JP,EST,False,NaN,B014,3965f26b,America/New_York
703,FEN-00684,2025-09-22 13:13:19+00:00,renew,FEN_C00140,user140@email.com,2025-04-07 14:52:53+00:00,GBR,Wales,CF10,standard_monthly,...,safari,ios,2560x1440,en-US,CET,False,NaN,B014,d4a24ffc,Europe/Berlin
704,FEN-00684,2025-09-22 13:13:19+00:00,renew,FEN_C00140,user140@email.com,2025-04-07 14:52:53+00:00,GBR,Wales,CF10,standard_monthly,...,safari,ios,2560x1440,en-US,CET,False,NaN,B014,d4a24ffc,Europe/Berlin
898,FEN-00901,2025-11-25 01:24:12+00:00,renew,FEN_C00142,user142@email.com,2025-04-03 15:01:48+00:00,GBR,Wales,CF10,standard_yearly,...,firefox,ios,1920x1080,de-DE,PST,False,NaN,B019,1ddd3040,America/Los_Angeles
899,FEN-00901,2025-11-25 01:24:12+00:00,renew,FEN_C00142,user142@email.com,2025-04-03 15:01:48+00:00,GBR,Wales,CF10,standard_yearly,...,firefox,ios,1920x1080,de-DE,PST,False,NaN,B019,1ddd3040,America/Los_Angeles
1003,FEN-00997,2025-12-24 18:24:12+00:00,renew,FEN_C00472,user472@email.com,2025-11-26 12:03:23+00:00,GBR,Scotland,EH1,standard_yearly,...,edge,macos,2560x1440,es-MX,CET,False,NaN,B020,add08d67,Europe/Berlin
1004,FEN-00997,2025-12-24 18:24:12+00:00,renew,FEN_C00472,user472@email.com,2025-11-26 12:03:23+00:00,GBR,Scotland,EH1,standard_yearly,...,edge,macos,2560x1440,es-MX,CET,False,NaN,B020,add08d67,Europe/Berlin
1128,FEN-01110,2026-02-05 19:45:57+00:00,cancel,FEN_C00050,user50@email.com,2025-02-14 07:22:16+00:00,USA,New York,10001,standard_monthly,...,edge,macos,1170x2532,ja-JP,AEST,False,NaN,B023,0d112f39,Australia/Sydney
1129,FEN-01110,2026-02-05 19:45:57+00:00,cancel,FEN_C00050,user50@email.com,2025-02-14 07:22:16+00:00,USA,New York,10001,standard_monthly,...,edge,macos,1170x2532,ja-JP,AEST,False,NaN,B023,0d112f39,Australia/Sydney

In [60]:
len(df_fenster_subscriptions[df_fenster_subscriptions.duplicated()])

11

In [71]:
df_fenster_subscriptions.plan.unique()

<StringArray>
['premium_monthly', 'standard_yearly', 'standard_monthly', 'premium_yearly']
Length: 4, dtype: str

In [74]:
df_fenster_subscriptions.type.unique()

<StringArray>
['new', 'renew', 'cancel', 'RENEW', 'NEW']
Length: 5, dtype: str

In [77]:
df_fenster_subscriptions.ccy.unique().tolist()

['USD']

In [75]:
url = "http://localhost:5050/exchange-rates"
df_exchange_rates = pd.read_csv(url)
print('Exchange Rates shape: ', df_exchange_rates.shape)
print('Exchange Rates columns: ', df_exchange_rates.iloc[0])
df_exchange_rates

Exchange Rates shape:  (13, 3)
Exchange Rates columns:  date           2025-02-01
currency              USD
rate_to_eur          0.92
Name: 0, dtype: object

          date currency  rate_to_eur
0   2025-02-01      USD         0.92
1   2025-03-01      USD         0.91
2   2025-04-01      USD         0.90
3   2025-05-01      USD         0.89
4   2025-06-01      USD         0.88
5   2025-07-01      USD         0.87
6   2025-08-01      USD         0.86
7   2025-09-01      USD         0.85
8   2025-10-01      USD         0.84
9   2025-11-01      USD         0.83
10  2025-12-01      USD         0.84
11  2026-01-01      USD         0.85
12  2026-02-01      USD         0.84

In [56]:
df_exchange_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         13 non-null     str
 1   currency     13 non-null     str
 2   rate_to_eur  13 non-null     float64
dtypes: float64(1), str(2)
memory usage: 444.0 bytes

In [68]:
date_columns = ['date']
for col in date_columns:
    df_exchange_rates[col] = pd.to_datetime(df_exchange_rates[col], errors='raise').dt.tz_localize('UTC')
df_exchange_rates.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         13 non-null     datetime64[us, UTC]
 1   currency     13 non-null     str
 2   rate_to_eur  13 non-null     float64
dtypes: datetime64[us, UTC](1), float64(1), str(1)
memory usage: 444.0 bytes